### ISSUE TITLE
bug (more than one decimal points)

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Qt-calculator#1]
you can add more than one decimals in the calculator.

**Comment by Arsenic-ATG** [comment]
i can fix it but it I am leaving it for any newcomer who want to collaborate in the project.

**Comment by aUsefulMethod** [comment]
I would like to attempt this, if that's ok?

**Comment by Arsenic-ATG** [comment]
@aUsefulMethod ok 👍
I am assigning you this task.
if you want more information about anything in the repository/project then feel free to ask.

**Comment by Arsenic-ATG** [comment]
@aUsefulMethod well done.
