### ISSUE TITLE
Can you update contributing.md ?

### ISSUE THREAD

**Issue by vivek80801** [Arsenic-ATG/Qt-calculator#12]
# You no longer need to remove build-Calculator-Desktop_Qt_5_15_1_GCC_64bit-Debug and Calculator.pro.user to remove.

Because these will be ignored by git by default. I don't know how folders get created during build time on other operating system.

```md
*.user

*.Debug
```

any file or folder with .user will be ignored
any file or folder With Debug will be ignored

I can updated contributing.md. But I am not sure about files or folder created on other operating system during build time.

**Comment by Arsenic-ATG** [comment]
[CONTRIBUTING.md](https://github.com/Arsenic-ATG/Qt-calculator/blob/master/CONTRIBUTING.md) has been updated as instructed in this issue

I will be revamping CONTRIBUTING.md soon in near future, that's why I have not updated a lot right now ( just removed the example )
