### ISSUE TITLE
Appending to label when it should not.

### ISSUE THREAD

**Issue by PJayakrishnan** [Arsenic-ATG/Qt-calculator#23]
**Describe the bug**
Digits of second number appends to first number after clearing.

**To Reproduce**
1. Open the Qt-calculator
2. Do some calculations and press clear (C) button.
3. Press any digit, say 4
4. Press any binary operator( +, -, x, /), say +.
5. Press any digit, say 8.
**Expected behavior**
Calculator takes first number as the first number itself (here 4). but what it takes as the second number is second number appended
to first number (here 48). Here we get 4 + 48 = 52 as answer when we need 4 + 8 = 12.

**Desktop (please complete the following information):**
 - OS: [windows 10]

**Additional context**
This bug is not seen for the calculations before C is pressed

**Comment by PJayakrishnan** [comment]
I worked on this issue for some time and is able to find a solution for this can I make a pull request for that?

**Comment by Arsenic-ATG** [comment]
> I worked on this issue for some time and is able to find a solution for this can I make a pull request for that?

sure, go ahead 

though, if you are planning to take part in this year's [hacktober fest](https://hacktoberfest.com), you might want to hold the PR till October 1st and open it later to make it count towards that.

**Comment by PJayakrishnan** [comment]
>  though, if you are planning to take part in this year's [hacktober fest](https://hacktoberfest.com/), you might want to hold the PR till October 1st and open it later to make it count towards that.

Thanks for letting me know about the fest. Just registered. Will make the PRs fromOctober 1.
