### ISSUE TITLE
making a scientific version of the same calculator

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Qt-calculator#3]
now the calculator can just perform generic calculations. it would be awesome to transform it to a fully functional scientific calculator.

**Comment by SakshiZ9** [comment]
Can I work on it?

**Comment by Arsenic-ATG** [comment]
@SakshiZ9 ok, I am assigning this issue to you.👍

**Comment by SakshiZ9** [comment]
Thank you for assigning the issue.
While Installing Qt application, there are two options default desktop installation and custom installation. Which one I should go for the installation process?

**Comment by Arsenic-ATG** [comment]
you can go with either of those

**Comment by SakshiZ9** [comment]
Thankyou.

**Comment by SakshiZ9** [comment]
I am facing an issue while installing the Qt application. It is showing Execution failed(Unexpected exit code:1603).How can I fix the issue?

**Comment by Arsenic-ATG** [comment]
Which Operating system are you using ?

**Comment by SakshiZ9** [comment]
Windows 10

**Comment by Arsenic-ATG** [comment]
Looks like the user **sdktool** doesn't have permissions to modify stuff in QtCreator installation folder.

just modify permissions on the whole Tools folder Qt installs and make sure Qt installation folder have all write permissions

If you don't know how to do that then have a look at this exmple👇
https://www.drivereasy.com/knowledge/error-1603-fatal-error-during-installation-fixed/

**Comment by SakshiZ9** [comment]
Thankyou the issue was resolved.

**Comment by SakshiZ9** [comment]
I cannot save the project, its showing it cannot be used as it is being used by another process. How to solve the issue?

**Comment by Arsenic-ATG** [comment]
did your program ran ?
if yes then the project would have been automatically saved and most probably the problem would be because you might have forgot to close the running instance of the project before quitting

**Comment by SakshiZ9** [comment]
When I changed the size of button 0 so that I could another button, I am not able to save it and showing the error as described earlier.

**Comment by Arsenic-ATG** [comment]
Are you using Dropbox/google-drive along with it or any other application with *file synchronisation* in it?

a conflict may occur due to that.

If so then closing it might solve the problem.

---

[source](https://forum.qt.io/topic/90796/error-while-saving-file-the-process-cannot-access-the-file-because-it-is-being-used-by-another-process)

**Comment by SakshiZ9** [comment]
Yes I am using Dropbox. Will close it and try to save the project.
Thank-you.

**Comment by SakshiZ9** [comment]
I have added a button () to make the calculation easy. But I am not able to write the code for that button. Can I get help with it?

**Comment by Arsenic-ATG** [comment]
you should probably look at the Qt documentation, of [How to Use QPushButton](https://wiki.qt.io/How_to_Use_QPushButton) to get a better understanding of working of QPushButton, I think they can explain it much better than me.

**Comment by SakshiZ9** [comment]
Okay.Thank you.

**Comment by eraviral34** [comment]
if possible I can help you in that as well

**Comment by Arsenic-ATG** [comment]
@eraviral34  yes this issue is open for everyone to contribute and there in not much that has been done till now on it. ( if you want to work exclusively on this issue then tell me to assign this issue ) 

I would recommend getting familiar with the project and Qt first. But still if you want or have worked with Qt before then I do let me know so that I assign you this issue 👍

**Comment by mahendra1290** [comment]
I have worked before on Qt can I work on this issue. I can develop it on Linux right ?

**Comment by Arsenic-ATG** [comment]
@mahendra1290 why not, go ahead 
if you need any help regarding the project then feel free to ask here or open a new issue regarding the same

**Comment by mahendra1290** [comment]
Yes
I want to start my open source journey

**Comment by mahendra1290** [comment]
The +, -, %, * are not showing in display on pressing but the calculation is correct. Is it a bug or anything else

**Comment by Arsenic-ATG** [comment]
@mahendra1290 no it's not a bug. It was supposed to work that way. The indicator of "which operation is going on" is the changed state of the button.

**Comment by mahendra1290** [comment]
I have added a new class for managing calculations and it will show all digits and operations like pocket calculator is that okay

**Comment by Prathamesh21Kulkarni** [comment]
Hey! Is the issue still open?
If yes I would like to contribute.

**Comment by Arsenic-ATG** [comment]
@Prathamesh21Kulkarni indeed, feel free to hack whatever you want and send a PR with the changes.

**Comment by Prathamesh21Kulkarni** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by moezmustafa** [comment]
Can you assign me the task ? i have recently worked with SFML and QT , to build a clone of super mario and would love to work on this project in my summer break

**Comment by Arsenic-ATG** [comment]
> Can you assign me the task ? i have recently worked with SFML and QT , to build a clone of super mario and would love to work on this project in my summer break

sure, feel free to give it a try

**Comment by moezmustafa** [comment]
> > Can you assign me the task ? i have recently worked with SFML and QT , to build a clone of super mario and would love to work on this project in my summer break
> 
> sure, feel free to give it a try

>awesome , ill Start working by 1st of August .

**Comment by PJayakrishnan** [comment]
Hello @Arsenic-ATG . By transforming did you mean to have a button for scientific and clicking it will show a new dialog with those scientific functions? Or entirely a new project or a scientific calculator itself, with labels, launched from this calculator?

**Comment by Arsenic-ATG** [comment]
> Hello @Arsenic-ATG . By transforming did you mean to have a button for scientific and clicking it will show a new dialog with those scientific functions? Or entirely a new project or a scientific calculator itself, with labels, launched from this calculator?

@PJayakrishnan , sorry for delayed response ( I was on a small vacation ) 
As for how to implement the scientific version of the calculator, feel free to take full creative freedom and do as you feel would be look better and be easier to implement for you.

**Comment by ofekkr1** [comment]
@Arsenic-ATG hello,
Im new to the open source related stuff,and I would like to contribute to the project.
May I be assigned to this issue?

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG hello,
> Im new to the open source related stuff,and I would like to contribute to the project.
> May I be assigned to this issue?

sure, I have assigned this issue to you 
Though this issue might look quite large at first, but I don't expect someone to implement all the features one would expect from a scientific calculator. Adding small changes ( adding one or two new functions ) should also work.

**Comment by ofekkr1** [comment]
@Arsenic-ATG Thank you for the fast response!
Im planning on making small PR as suggested, will update on my progress.

**Comment by ofekkr1** [comment]
@Arsenic-ATG sorry for the misunderstending, there was a missclick the unassigned me from the issue.
May you please reassign me when you can?

**Comment by ofekkr1** [comment]
hi,
I made a PR at #29 , which added some functionality to the calculator(had to change the buttons location, hope you dont mind).

**Comment by ofekkr1** [comment]
@Arsenic-ATG hi,
Just letting you know I made another PR at #30, I will focus on tests and bug fixing on the next PR
