### ISSUE TITLE
Adding unit tests

### ISSUE THREAD

**Issue by ofekkr1** [Arsenic-ATG/Qt-calculator#31]
## Feature
As more features are being added to the calculator, we need to make sure that everything that was added before, is still working as intended.

## Solution
This can be solved by adding unit tests from qt itself(although adding tests to an existing project is quite hard in qt).

**Comment by ofekkr1** [comment]
@Arsenic-ATG May I work on this one?

**Comment by ofekkr1** [comment]
@Arsenic-ATG I made a new PR at #32 , but the tests are still not automated(there is no direct way to test qt with github workflow, only with Cmake which has its own bugs on qt).

**Comment by TNomura-04** [comment]
can I work on this?
