### ISSUE TITLE
QPalette::Background is now Depreciated

### ISSUE THREAD

**Issue by adesolasamuel** [Arsenic-ATG/Qt-calculator#44]
**Describe the bug**
QPalette::Background is now Depreciated which makes the source code not to run

**To Reproduce**
Try Building the source code

**Expected behavior**
The code is supposed to build successfully

**Desktop (please complete the following information):**
 - OS: Linus Ubuntu
 - Browser chrome
 - Version 22.04

**Smartphone (please complete the following information):**

**Additional context**
I have worked on this Bug and ready to submit a pull request

**Comment by ofekkr1** [comment]
hi @adesolasamuel 
thank you for the contribution.
I will make sure to review the pull request you sent as soon as possible
