### ISSUE TITLE
Changing the theme of the calculator

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Qt-calculator#5]
current theme of calculator is pretty basic, it would be amazing to have different themes of the same.

if anyone have any ideas regarding the same then they can discuss it here.

ideas may include changes in :-
1) layout
2) colour pallet
3) overall design

**Comment by IshuSingh1** [comment]
The buttons are too edgy, round edges would be nicer.

**Comment by Arsenic-ATG** [comment]
@IshuSingh1 thanks for the suggestion 😃

here is how calculator will look after the corners would be rounded👇
![rounded corner theme](https://github.com/Arsenic-ATG/Qt-calculator/blob/master/screenshots/rounded%20corner%20theme.png)

**Comment by vivek80801** [comment]
Add some margin between buttons if possible.
Add some margin between border of calculator and buttons
Buttons looks to big. reduce padding on buttons.

I did not this issue first so I had opened another issue.

**Comment by Arsenic-ATG** [comment]
Thanks @vivek80801 for the suggestion 😃

I would be working on it, or if you want to work on it then do let me know.

**Comment by ahmedellord56** [comment]
Can you give me some instruction on how to do so?
Its my first contribution , So I lack experience.

**Comment by Arsenic-ATG** [comment]
@ahmedellord56 changing the front end requires pure CSS skills : - 
1) Set up the Qt creator and get the project configured on as instructed in [README.md](https://github.com/Arsenic-ATG/Qt-calculator/blob/master/README.md) file

2) Go to `mainwindow.ui` inside the foler `Forms`
<img width="238" alt="Screenshot 2020-10-18 at 6 50 52 AM" src="https://user-images.githubusercontent.com/54987647/96356591-45037180-110e-11eb-9d0f-80d25dd88294.png">


3) Select the area you want to alter ( for example let say you want to change the colour of a button, so click on the required button) and then search for its stylesheets and alter them accordingly. 
<img width="760" alt="Screenshot 2020-10-18 at 6 57 50 AM" src="https://user-images.githubusercontent.com/54987647/96356646-3e292e80-110f-11eb-87ce-74d4b17d961b.png">

4) Commit your changes to your fork and then open a pull request here.

> ⚠️ ScreenShots used here are taken on a system running macOS operating system, results may vary depending on the operating system you are running in your device

**Comment by vivek80801** [comment]
@ahmedellord56 

there is design button on left sidebar in qt creator. you can also use that.

**Comment by SakshiZ9** [comment]
Can I contribute to the project by changing the sequence of the numbers and also adding some more buttons?

**Comment by Arsenic-ATG** [comment]
@SakshiZ9 why not, go for it.🙂 
I would be waiting for your contribution

**Comment by vivek80801** [comment]
@SakshiZ9 we will love to see your contributions.  If you have some questions feel free to ask. We will try to give answers as soon as possible.

**Comment by SakshiZ9** [comment]
I have made few changes and requested a pull request. Kindly let know to add any changes in the project.

**Comment by Arsenic-ATG** [comment]
@SakshiZ9 I can't see any pull request on this repository or on your fork, are you sure you pushed the commits to your remote repository after doing all the changes in your local repository. or either you have not committed those changes.

**Comment by SakshiZ9** [comment]
Okay. I tried it again, is there any pull request from my side?

**Comment by eraviral34** [comment]
Hi guys, i would like to contribute to this project 
is there anything where I can contribute

**Comment by Arsenic-ATG** [comment]
> Hi guys, i would like to contribute to this project
> is there anything where I can contribute
> @Arsenic-ATG
> @vivek80801

@eraviral34 thanks for choosing this repository to contribute we love contributions 🙂

right now there are 3 places where you can contribute : -
1) changing the front end of the calculator
2) working on backend or adding more functionality to the calculator (like discussed in [this](https://github.com/Arsenic-ATG/Qt-calculator/issues/3) issue ) if you want to add any other functionality then just open a new issue regarding the same.
3) contributing on documentation :- if you find any fault/typo in documentation ( readme.md, contributing.md etc) or you think there is something this you could have explained better or something then feel free to change it and send a PR for us to review and merge

**Comment by eraviral34** [comment]
I would like to work more on a backend

**Comment by Arsenic-ATG** [comment]
@eraviral34 good, then you can either work on the [scientific calculator issue](https://github.com/Arsenic-ATG/Qt-calculator/issues/3) or open a new one regarding any functionality you wish to add

**Comment by iPraveenParihar** [comment]
@Arsenic-ATG  About the theme, we can try vibrant colors for operator buttons.
For example, I designed this simple CSS to show 
![image](https://user-images.githubusercontent.com/30765265/104936583-ba633480-59d2-11eb-85be-fa0593bf2b45.png)

**Comment by Arsenic-ATG** [comment]
@iPraveenParihar that looks amazing. I would look forward to adding those soon. 

Or

If you are interested in doing it yourself ?

**Comment by iPraveenParihar** [comment]
@Arsenic-ATG, Not now currently working on another project. And also am not familiar with QT

**Comment by vivek80801** [comment]
@iPraveenParihar  Thanks for redesigning the app. QT has GUI to do to design the app. all the code will generated by that QT itself.

@Arsenic-ATG  Can I try to implement new design ?

**Comment by Arsenic-ATG** [comment]
sure @vivek80801 , go for it.

**Comment by sheharyaar** [comment]
@Arsenic-ATG Can we add a dark mode to the calculator?? It would be much better with the dark mode in wide use these days.

**Comment by Arsenic-ATG** [comment]
@sheharyaar sure, go ahead. If you want any help from me about the project of Qt in general then feel free to ask.

**Comment by Paiz0** [comment]
@Arsenic-ATG Hey, can I contribute to this and make a "matrix" (think green on black) styled theme?

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG Hey, can I contribute to this and make a "matrix" (think green on black) styled theme?

Sure go for it.

**Comment by Codebat-man** [comment]
<head>
  <script language="javascript"></script>
</head>
<form name="sci-calc">
 <table class="calculator" cellspacing="0" cellpadding="1">
   <tr>
     <td colspan="5"><input id="display" name="display" value="0" size="28" maxlength="25"></td>
   </tr>
   <tr>
     <td><input type="button" class="btnTop" name="btnTop" value="C" onclick="this.form.display.value=  0 "></td>
     <td><input type="button" class="btnTop" name="btnTop" value="<--" onclick="deleteChar(this.form.display)"></td>
     <td><input type="button" class="btnTop" name="btnTop" value="=" onclick="if(checkNum(this.form.display.value)) { compute(this.form) }"></td>
     <td><input type="button" class="btnOpps" name="btnOpps" value="&#960;" onclick="addChar(this.form.display,'3.14159265359')"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="%" onclick=" percent(this.form.display)"></td>
   </tr>
   <tr>
     <td><input type="button" class="btnNum" name="btnNum" value="7" onclick="addChar(this.form.display, '7')"></td>
     <td><input type="button" class="btnNum" name="btnNum" value="8" onclick="addChar(this.form.display, '8')"></td>
     <td><input type="button" class="btnNum" name="btnNum" value="9" onclick="addChar(this.form.display, '9')"></td>
     <td><input type="button" class="btnOpps" name="btnOpps" value="x&#94;" onclick="if(checkNum(this.form.display.value)) { exp(this.form) }"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="/" onclick="addChar(this.form.display, '/')"></td>
   <tr>
     <td><input type="button" class="btnNum" name="btnNum" value="4" onclick="addChar(this.form.display, '4')"></td>
     <td><input type="button" class="btnNum" name="btnNum" value="5" onclick="addChar(this.form.display, '5')"></td>
     <td><input type="button" class="btnNum" name="btnNum" value="6" onclick="addChar(this.form.display, '6')"></td>
     <td><input type="button" class="btnOpps" name="btnOpps" value="ln" onclick="if(checkNum(this.form.display.value)) { ln(this.form) }"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="*" onclick="addChar(this.form.display, '*')"></td>
   </tr>
   <tr>
     <td><input type="button" class="btnNum" name="btnNum" value="1" onclick="addChar(this.form.display, '1')"></td>
     <td><input type="button" class="btnNum" name="btnNum" value="2" onclick="addChar(this.form.display, '2')"></td>
     <td><input type="button" class="btnNum" name="btnNum" value="3" onclick="addChar(this.form.display, '3')"></td>
     <td><input type="button" class="btnOpps" name="btnOpps" value="&radic;" onclick="if(checkNum(this.form.display.value)) { sqrt(this.form) }"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="-" onclick="addChar(this.form.display, '-')"></td>
   </tr>
   <tr>
     <td><input type="button" class="btnMath" name="btnMath" value="&#177" onclick="changeSign(this.form.display)"></td>
     <td><input type="button" class="btnNum" name="btnNum" value="0" onclick="addChar(this.form.display, '0')"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="&#46;" onclick="addChar(this.form.display, '&#46;')"></td>
     <td><input type="button" class="btnOpps" name="btnOpps" value="x&#50;" onclick="if(checkNum(this.form.display.value)) { square(this.form) }"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="+" onclick="addChar(this.form.display, '+')"></td>
   </tr>
   <tr>
     <td><input type="button" class="btnMath" name="btnMath" value="(" onclick="addChar(this.form.display, '(')"></td>
     <td><input type="button" class="btnMath" name="btnMath" value=")" onclick="addChar(this.form.display,')')"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="cos" onclick="if(checkNum(this.form.display.value)) { cos(this.form) }"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="sin" onclick="if(checkNum(this.form.display.value)) { sin(this.form) }"></td>
     <td><input type="button" class="btnMath" name="btnMath" value="tan" onclick="if(checkNum(this.form.display.value)) { tan(this.form) }"></td>
  </tr>
 </tabel>
</form>

* {
  padding: 0;
  margin: 5px;
  text-align: center;
}
body {
  background-color:blue;
}
.calculator {
  width: 350px;
  height: 320px;
  background-color: #c0c0c0;
  box-shadow: 0px 0px 0px 10px #666;
  border: 5px solid black;
  border-radius: 10px;
}
#display {
  width: 320px;
  height: 40px;
  text-align: right;
  background-color: black;
  border: 3px solid white;
  font-size: 18px;
  left: 2px;
  top: 2px;
  color: #7fff00;
}
.btnTop{
  color: white;
  background-color: #6f6f6f;
  font-size: 14px;
  margin: auto;
  width: 50px;
  height: 25px;
}
.btnNum {
  color: white;
  background-color: black;
  font-size: 14px;
  margin: auto;
  width: 50px;
  height: 25px;
}
.btnMath {
  color: white;
  background-color: #ff4561;
  font-size: 14px;
  margin: auto;
  width: 50px;
  height: 25px;
}
.btnOpps {
  color: white;
  background-color: #ff9933;
  font-size: 14px;
  margin: auto;
  width: 50px;
  height: 25px;
}
function addChar(input, character) {
	if(input.value == null || input.value == "0")
		input.value = character
	else
		input.value += character
}

function cos(form) {
	form.display.value = Math.cos(form.display.value);
}

function sin(form) {
	form.display.value = Math.sin(form.display.value);
}

function tan(form) {
	form.display.value = Math.tan(form.display.value);
}

function sqrt(form) {
	form.display.value = Math.sqrt(form.display.value);
}

function ln(form) {
	form.display.value = Math.log(form.display.value);
}

function exp(form) {
	form.display.value = Math.exp(form.display.value);
}

function deleteChar(input) {
	input.value = input.value.substring(0, input.value.length - 1)
}
var val = 0.0;
function percent(input) {
  val = input.value;
  input.value = input.value + "%";
}

function changeSign(input) {
	if(input.value.substring(0, 1) == "-")
		input.value = input.value.substring(1, input.value.length)
	else
		input.value = "-" + input.value
}

function compute(form) {
  //if (val !== 0.0) {
   // var percent = form.display.value;  
   // percent = pcent.substring(percent.indexOf("%")+1);
   // form.display.value = parseFloat(percent)/100 * val;
    //val = 0.0;
 // } else 
    form.display.value = eval(form.display.value);
  }


function square(form) {
	form.display.value = eval(form.display.value) * eval(form.display.value)
}

function checkNum(str) {
	for (var i = 0; i < str.length; i++) {
		var ch = str.charAt(i);
		if (ch < "0" || ch > "9") {
			if (ch != "/" && ch != "*" && ch != "+" && ch != "-" && ch != "."
				&& ch != "(" && ch!= ")" && ch != "%") {
				alert("invalid entry!")
				return false
				}
			}
		}
		return true
}

![Screenshot (158)](https://user-images.githubusercontent.com/66846495/136028338-de8d2e47-63a0-4c17-9f0a-293dd9ca4e95.png)

**Comment by garvitrai013** [comment]
What are the demands/requirements for themes that have to be met in this project?

I'm interested to contribute here

**Comment by Arsenic-ATG** [comment]
> What are the demands/requirements for themes that have to be met in this project?
> 
> I'm interested to contribute here

There aren't any specific requirements for the theme apart from the fact that it should cover all the functional buttons on the calculator, feel free to take full creative freedom with the UI.

**Comment by QDaily117** [comment]
Hey @Arsenic-ATG I am new to open source issues, and was wondering if I could help with the front end of this calculator. Maybe add a Rainbow Theme or some other theme if that one has already been accomplished.

**Comment by Arsenic-ATG** [comment]
> Hey @Arsenic-ATG I am new to open source issues, and was wondering if I could help with the front end of this calculator. Maybe add a Rainbow Theme or some other theme if that one has already been accomplished.

Hi @QDaily117 (sorry for late reply)
Could you please elaborate a bit about what exactly do you mean by rainbow theme ? 
or better send in a PR with the changes and we can check/alter the theme during review process only. 👍

**Comment by Haricharan0310** [comment]
Hey! @Arsenic-ATG I'm new to open source and I was wondering If I could contribute on this Issue.
I was thinking maybe have no border between the buttons and change the font ,it makes them more clean in my opinion.

**Comment by Arsenic-ATG** [comment]
@Haricharan0310 sure, feel free to alter the theme.

plus I am planning to register this project in [hacktober fest](https://hacktoberfest.com), so if you are also registering and planning to make this contribution count there also then do let me know.

**Comment by Haricharan0310** [comment]
@Arsenic-ATG Yes, I'm interested in registering to the hacktober fest, thank you for this Information.

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG Yes, I'm interested in registering to the hacktober fest, thank you for this Information.

nice to hear that, just make sure to open the PR after October 1st

**Comment by Haricharan0310** [comment]
Sure, thanks again! @Arsenic-ATG

**Comment by PJayakrishnan** [comment]
Hi @Arsenic-ATG  @everyOne, I am interested in contributing to this project.  Will that be cool if I change the MainWindow back ground color? If yes, do anyone have any suggestions with the color which go hand in hand with other button colors?

**Comment by Arsenic-ATG** [comment]
> Hi @Arsenic-ATG https://github.com/everyone, I am interested in contributing to this project. Will that be cool if I change the MainWindow back ground color? If yes, do anyone have any suggestions with the color which go hand in hand with other button colors?
@PJayakrishnan just make a PR regarding the same and we can see how it looks then.

> I did find a small bug in the back end as well. I cam up with a solution. Can we discuss it here itself or is there some other way?

feel free to open a new issue regarding the same

**Comment by PJayakrishnan** [comment]
> > @PJayakrishnan just make a PR regarding the same and we can see how it looks then.

![Screenshot (99)](https://user-images.githubusercontent.com/96824788/192502056-cfbc97dd-18bd-4a2a-9eb8-fbfac0fe2239.png)
I tried this color for some contrast between buttons. I am not that artistic so other people's suggestions might be more good.

> > feel free to open a new issue regarding the same

I will do that.

**Comment by Kashish-gitt** [comment]
hii @Arsenic-ATG i am interested in contributing in this project is there anything in which i can contribute?

**Comment by Arsenic-ATG** [comment]
> hii @Arsenic-ATG i am interested in contributing in this project is there anything in which i can contribute?

hi @Kashish-gitt , you can always update the current theme and update it too look much better, or if you want you can also expand the functionality of the calculator by adding more arithmetic functions to it ( like `log` or even brackets `()` to specify precedence ), the later would come under #3 but you can always open a new issue and add a small functionality on your own.

**Comment by Anteneh13** [comment]
Im interested in contributing to this project if im still able too?

**Comment by tanmay-devv** [comment]
Hey @Arsenic-ATG are there any contributions that I can make to this?

**Comment by safe049** [comment]
@Arsenic-ATG Hello,i drew a lot and got some ideas on the colors, may i contributing to this project too?

**Comment by Manas-salian** [comment]
@Haricharan0310 hello, can i still contribute to this isssue?

**Comment by Arsenic-ATG** [comment]
we don't need more themes or now 

closing this issue (might reopen it or create a new tracking issue in future regarding themes

Thanks all for contributing to the project.
